import type { DemoDisarmTransitionConfig } from "./DemoDisarmTransitionModel.ts";

const DESIGN_WIDTH = 1280;
const DESIGN_HEIGHT = 720;

/** D4.1 第一阶段左轮夺械灰盒参数。 */
export const DEMO_PHASE1_DISARM_CONFIG: Readonly<DemoDisarmTransitionConfig> =
  Object.freeze({
    weaponKind: "revolver",
    weaponLabel: "左轮手枪",
    attackMode: "projectile",
    randomSeed: 2026094101,
    throwDurationSeconds: 0.8,
    throwArcHeight: 150,
    landingBounds: Object.freeze({
      minX: 350,
      maxX: 570,
      minY: 210,
      maxY: 560,
    }),
    weaponRadius: 30,
    heldWeaponOffset: Object.freeze({ x: 72, y: -18 }),
    muzzleOffset: 58,
    fireIntervalSeconds: 0.32,
    projectilesPerShot: 1,
    projectileSpreadRadians: 0,
    projectileSpeed: 560,
    projectileAcceleration: 0,
    projectileMaximumSpeed: 560,
    projectileRadius: 10,
    requiredHits: 16,
    discardVelocity: Object.freeze({ x: -150, y: -220 }),
    discardGravity: 900,
    discardSeconds: 1.6,
    worldWidth: DESIGN_WIDTH,
    worldHeight: DESIGN_HEIGHT,
    despawnPadding: 60,
  });

/** D4.2 第二阶段 AK47 夺械灰盒参数。 */
export const DEMO_PHASE2_DISARM_CONFIG: Readonly<DemoDisarmTransitionConfig> =
  Object.freeze({
    weaponKind: "ak47",
    weaponLabel: "AK47",
    attackMode: "projectile",
    randomSeed: 2026094202,
    throwDurationSeconds: 0.85,
    throwArcHeight: 145,
    landingBounds: Object.freeze({
      minX: 330,
      maxX: 560,
      minY: 200,
      maxY: 550,
    }),
    weaponRadius: 38,
    heldWeaponOffset: Object.freeze({ x: 82, y: -18 }),
    muzzleOffset: 82,
    fireIntervalSeconds: 0.16,
    projectilesPerShot: 1,
    projectileSpreadRadians: 0,
    projectileSpeed: 650,
    projectileAcceleration: 0,
    projectileMaximumSpeed: 650,
    projectileRadius: 9,
    requiredHits: 32,
    discardVelocity: Object.freeze({ x: -170, y: -235 }),
    discardGravity: 900,
    discardSeconds: 1.6,
    worldWidth: DESIGN_WIDTH,
    worldHeight: DESIGN_HEIGHT,
    despawnPadding: 60,
  });

/** D4.3 第三阶段霰弹枪夺械灰盒参数。 */
export const DEMO_PHASE3_SHOTGUN_DISARM_CONFIG: Readonly<DemoDisarmTransitionConfig> =
  Object.freeze({
    weaponKind: "shotgun",
    weaponLabel: "霰弹枪",
    attackMode: "projectile",
    randomSeed: 2026094303,
    throwDurationSeconds: 0.85,
    throwArcHeight: 150,
    landingBounds: Object.freeze({
      minX: 330,
      maxX: 560,
      minY: 195,
      maxY: 550,
    }),
    weaponRadius: 40,
    heldWeaponOffset: Object.freeze({ x: 84, y: -18 }),
    muzzleOffset: 88,
    fireIntervalSeconds: 0.8,
    projectilesPerShot: 6,
    projectileSpreadRadians: 0.12,
    projectileSpeed: 530,
    projectileAcceleration: 0,
    projectileMaximumSpeed: 530,
    projectileRadius: 8,
    requiredHits: 36,
    discardVelocity: Object.freeze({ x: -175, y: -240 }),
    discardGravity: 900,
    discardSeconds: 1.6,
    worldWidth: DESIGN_WIDTH,
    worldHeight: DESIGN_HEIGHT,
    despawnPadding: 60,
  });

/** D4.3 第三阶段火箭发射器夺械灰盒参数。 */
export const DEMO_PHASE3_ROCKET_DISARM_CONFIG: Readonly<DemoDisarmTransitionConfig> =
  Object.freeze({
    weaponKind: "rocket-launcher",
    weaponLabel: "火箭发射器",
    attackMode: "projectile",
    randomSeed: 2026094313,
    throwDurationSeconds: 0.9,
    throwArcHeight: 145,
    landingBounds: Object.freeze({
      minX: 320,
      maxX: 540,
      minY: 200,
      maxY: 545,
    }),
    weaponRadius: 44,
    heldWeaponOffset: Object.freeze({ x: 88, y: -20 }),
    muzzleOffset: 92,
    fireIntervalSeconds: 0.75,
    projectilesPerShot: 1,
    projectileSpreadRadians: 0,
    projectileSpeed: 0,
    projectileAcceleration: 700,
    projectileMaximumSpeed: 560,
    projectileRadius: 20,
    requiredHits: 6,
    discardVelocity: Object.freeze({ x: -180, y: -245 }),
    discardGravity: 900,
    discardSeconds: 1.7,
    worldWidth: DESIGN_WIDTH,
    worldHeight: DESIGN_HEIGHT,
    despawnPadding: 80,
  });

/** D4.4 第四阶段召唤器夺械灰盒参数。 */
export const DEMO_PHASE4_SUMMONER_DISARM_CONFIG: Readonly<DemoDisarmTransitionConfig> =
  Object.freeze({
    weaponKind: "summoner",
    weaponLabel: "召唤器",
    attackMode: "creeper",
    randomSeed: 2026094404,
    throwDurationSeconds: 0.85,
    throwArcHeight: 155,
    landingBounds: Object.freeze({
      minX: 330,
      maxX: 560,
      minY: 195,
      maxY: 550,
    }),
    weaponRadius: 38,
    heldWeaponOffset: Object.freeze({ x: 76, y: -22 }),
    muzzleOffset: 60,
    fireIntervalSeconds: 0.65,
    projectilesPerShot: 1,
    projectileSpreadRadians: 0,
    projectileSpeed: 0,
    projectileAcceleration: 0,
    projectileMaximumSpeed: 0,
    projectileRadius: 1,
    requiredHits: 4,
    discardVelocity: Object.freeze({ x: -165, y: -235 }),
    discardGravity: 900,
    discardSeconds: 1.6,
    worldWidth: DESIGN_WIDTH,
    worldHeight: DESIGN_HEIGHT,
    despawnPadding: 60,
    creeper: Object.freeze({
      maximumActive: 5,
      radius: 25,
      trackingSpeed: 360,
      triggerDistance: 72,
      castSeconds: 0.45,
      explosionSeconds: 0.3,
      explosionRadius: 84,
    }),
  });

/** D4.5 第五阶段激光枪最终夺械灰盒参数。 */
export const DEMO_PHASE5_LASER_DISARM_CONFIG: Readonly<DemoDisarmTransitionConfig> =
  Object.freeze({
    weaponKind: "laser-gun",
    weaponLabel: "激光枪",
    attackMode: "laser",
    randomSeed: 2026094505,
    throwDurationSeconds: 0.9,
    throwArcHeight: 165,
    landingBounds: Object.freeze({
      minX: 320,
      maxX: 540,
      minY: 195,
      maxY: 545,
    }),
    weaponRadius: 42,
    heldWeaponOffset: Object.freeze({ x: 86, y: -22 }),
    muzzleOffset: 92,
    fireIntervalSeconds: 0.1,
    projectilesPerShot: 1,
    projectileSpreadRadians: 0,
    projectileSpeed: 0,
    projectileAcceleration: 0,
    projectileMaximumSpeed: 0,
    projectileRadius: 1,
    requiredHits: 5,
    discardVelocity: Object.freeze({ x: -185, y: -255 }),
    discardGravity: 900,
    discardSeconds: 1.8,
    worldWidth: DESIGN_WIDTH,
    worldHeight: DESIGN_HEIGHT,
    despawnPadding: 80,
    laser: Object.freeze({
      chargeSeconds: 0.65,
      pressurePerSecond: 1,
      beamHalfWidth: 48,
    }),
  });
